positions:
- ticker: VOO
  shares: 0.0
- ticker: VO
  shares: 0.0
- ticker: VEA
  shares: 0.0
- ticker: IEMG
  shares: 0.0
- ticker: REET
  shares: 0.0
- ticker: GLD
  shares: 0.0
- ticker: BCI
  shares: 0.0
- ticker: IXC
  shares: 0.0
- ticker: VGIT
  shares: 0.0
- ticker: USFR
  shares: 0.0
